new GameTSCtrl(GameViewGui) {
   isContainer = true;
   profile = GuiDefaultProfile;
   horizSizing = "right";
   vertSizing = "bottom";
   position = "0 0";
   extent = "1024 768";
   minExtent = "8 8";
   canSave = true;
   visible = true;
   margin = "0 0 0 0";
   padding = "0 0 0 0";
   anchorTop = true;
   anchorBottom = false;
   anchorLeft = true;
   anchorRight = false;
   cameraZRot = false;
   forceFOV = false;
   enabled = true;
   helpTag = false;
   noCursor = true;
};
